service: servicio-vuelos-destino

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  environment:
    DESTINOS_TABLE: ${self:service}-${self:provider.stage}-destinos
  iam:
    role: arn:aws:iam::498917627164:role/LabRole

functions:
  crearDestino:
    handler: crearDestino.handler
    events:
      - http:
          path: /destinos
          method: post
          cors: true
          integration: lambda

  obtenerDestinos:
    handler: obtenerDestinos.handler
    events:
      - http:
          path: /destinos
          method: get
          cors: true

  modificarDestino:
    handler: modificarDestino.handler
    events:
      - http:
          path: /destinos
          method: put
          cors: true

  eliminarDestino:
    handler: eliminarDestino.handler
    events:
      - http:
          path: /destinos
          method: delete
          cors: true
  obtenerDestinoById:
    handler: ObtenerDestinoById.handler
    events:
      - http:
          path: /destinos/{id_destino}
          method: get
          cors: true

resources:
  Resources:
    DestinosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DESTINOS_TABLE}
        AttributeDefinitions:
          - AttributeName: id_destino
            AttributeType: S
          - AttributeName: ciudad
            AttributeType: S
          - AttributeName: pais
            AttributeType: S   # LSI para búsqueda por país
          - AttributeName: popularidad
            AttributeType: N   # GSI para ordenar por popularidad
        KeySchema:
          - AttributeName: id_destino
            KeyType: HASH
          - AttributeName: ciudad
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

        # Índice Secundario Local (LSI)
        LocalSecondaryIndexes:
          - IndexName: PaisIndex
            KeySchema:
              - AttributeName: id_destino
                KeyType: HASH
              - AttributeName: pais
                KeyType: RANGE
            Projection:
              ProjectionType: ALL

        # Índice Secundario Global (GSI)
        GlobalSecondaryIndexes:
          - IndexName: PopularidadIndex
            KeySchema:
              - AttributeName: popularidad
                KeyType: HASH
              - AttributeName: ciudad
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
